[package]
name = "curve_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
uint = "0.9"

[package.metadata]
descrtiption = "General purpose bonding curve library for pizza.fun"
license = "MIT"
